apiVersion: apps/v1
kind: Deployment
metadata:
  name:  paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  minReadySeconds: 10    
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0 # Количество реплик, которое можно создать с превышением значения replicas
      maxUnavailable: 1 # Количество реплик от общего числа, которое можно "уронить"
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: server
        image: pyankov/k8s-intro-paymentservice:0.0.1
